Fixes for shared library build on Mac

diff --git a/build/pkgs/scipoptsuite/spkg-install b/build/pkgs/scipoptsuite/spkg-install
--- a/build/pkgs/scipoptsuite/spkg-install
+++ b/build/pkgs/scipoptsuite/spkg-install
@@ -59,13 +59,16 @@ SCIP_DIR=`find . -name "scip-*" -type d`
 SCIP_DIR=`basename $SCIP_DIR`
 SCIP_VERSION=`echo "$SCIP_DIR" | sed -e "s/.*-//"`
 
+
+# Apply patch to SCIP.
+(cd $SCIP_DIR && patch -p1 < ../patches/scip-libdep.patch || ( echo >&2 "Error applying 'scip-libdep.patch'"; exit 1 ) )
+
 echo "Compiling SoPlex"
 
-# it's really necessary to say zlib=false, otherwise i got "unknown
-# symbol: gzwrite" when loading scip is there no zlib in sage?!
-
 cd $SRC/$SOPLEX_DIR
-make OPT=opt ZLIB=false READLINE=false SHARED=true USRCFLAGS="$CFLAGS"
+## The Makefile in soplex 2.2.1 forgets to add the library dependencies
+## "-lgmp -lz", causing the link to fail on Mac OS X.
+make VERBOSE=true OPT=opt ZLIB=true READLINE=true SHARED=true USRCFLAGS="$CFLAGS" LIBBUILDFLAGS="$LDFLAGS -shared -lgmp -lz "
 
 if [ $? -ne 0 ]; then
     echo "Error building SOPLEX."
@@ -89,36 +92,39 @@ echo "Compiling SCIP"
 
 cd $SRC/$SCIP_DIR
 # for clp add the option LPS=clp
-make OPT=opt SHARED=true ZIMPL=false GMP=true ZLIB=false READLINE=false USRCFLAGS="$CFLAGS"
+## added -rpath.  Abusing LIBBUILD_o is of course a hack. 
+make OPT=opt VERBOSE=true SHARED=true ZIMPL=false GMP=true ZLIB=true READLINE=true USRCFLAGS="$CFLAGS" USRLDFLAGS="-Wl,-rpath,$SAGE_LOCAL/lib" \
+ LIBBUILD_o="-Wl,-rpath,$SAGE_LOCAL/lib -o " INSTALLDIR="$SAGE_LOCAL" install
 
 if [ $? -ne 0 ]; then
     echo "Error building SCIP"
     exit 1
 fi
 
-cp lib/libscip*.so "$SAGE_LOCAL"/lib
-cp lib/liblpispx*.so "$SAGE_LOCAL"/lib
-cp lib/libnlpi*.so "$SAGE_LOCAL"/lib
-cp lib/libobjscip*.so "$SAGE_LOCAL"/lib
+## TODO: use make.install from scip??
+## cp lib/libscip*.so "$SAGE_LOCAL"/lib
+## cp lib/liblpispx*.so "$SAGE_LOCAL"/lib
+## cp lib/libnlpi*.so "$SAGE_LOCAL"/lib
+## cp lib/libobjscip*.so "$SAGE_LOCAL"/lib
 
-if [ ! -d $SAGE_LOCAL/include/scip ]; then
-   mkdir $SAGE_LOCAL/include/scip
-fi
+## if [ ! -d $SAGE_LOCAL/include/scip ]; then
+##    mkdir $SAGE_LOCAL/include/scip
+## fi
 
-cp -r src/scip/*.h "$SAGE_LOCAL"/include/scip/
+## cp -r src/scip/*.h "$SAGE_LOCAL"/include/scip/
 
-if [ ! -d $SAGE_LOCAL/include/blockmemshell ]; then
-   mkdir $SAGE_LOCAL/include/blockmemshell
-fi
+## if [ ! -d $SAGE_LOCAL/include/blockmemshell ]; then
+##    mkdir $SAGE_LOCAL/include/blockmemshell
+## fi
 
-cp -r src/blockmemshell/*.h "$SAGE_LOCAL"/include/blockmemshell
+## cp -r src/blockmemshell/*.h "$SAGE_LOCAL"/include/blockmemshell
 
 
-if [ ! -d $SAGE_LOCAL/include/nlpi ]; then
-   mkdir $SAGE_LOCAL/include/nlpi
-fi
+## if [ ! -d $SAGE_LOCAL/include/nlpi ]; then
+##    mkdir $SAGE_LOCAL/include/nlpi
+## fi
 
-cp -r src/nlpi/*.h "$SAGE_LOCAL"/include/nlpi
+## cp -r src/nlpi/*.h "$SAGE_LOCAL"/include/nlpi
 
 
 echo "finished building SCIP with SoPlex"
