Classes DegenerateManifold and DegenerateSubmanifold

diff --git a/build/pkgs/mpfr/spkg-install b/build/pkgs/mpfr/spkg-install
--- a/build/pkgs/mpfr/spkg-install
+++ b/build/pkgs/mpfr/spkg-install
@@ -1,3 +1,10 @@
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "Error: SAGE_LOCAL undefined - exiting..."
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
+fi
+
+
 mpfr_get_upstream_selected_cflags() # Get MPFR's choice on empty CC and CFLAGS.
 {
     if [ $# -ne 1 ]; then
@@ -139,14 +146,31 @@ mpfr_configure()
         echo "You can set MPFR_CONFIGURE to pass additional parameters."
     fi
 
-    sdh_configure --with-gmp="$SAGE_LOCAL" \
+    ./configure --prefix="$SAGE_LOCAL" \
+                --libdir="$SAGE_LOCAL/lib" \
+                --with-gmp="$SAGE_LOCAL" \
                 $SAGE_CONF_OPTS $MPFR_CONFIGURE
 }
 
 mpfr_build()
 {
+    echo "Configuring MPFR..."
     mpfr_configure
-    sdh_make
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error configuring MPFR."
+        echo >&2 "See above for the options passed to it, and the file"
+        echo >&2 "  `pwd`/config.log"
+        echo >&2 "for details."
+        exit 1
+    fi
+
+    echo
+    echo "Now building MPFR..."
+    $MAKE
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error building MPFR."
+        exit 1
+    fi
 
     echo
     echo "Building MPFR succeeded.  Now deleting old headers..."
@@ -155,9 +179,15 @@ mpfr_build()
     # parallel builds.
     # rm -f "$SAGE_LOCAL"/lib/libmpfr.*
 
-    sdh_make_install
+    echo "Now installing MPFR..."
+    $MAKE install
+    if [ $? -ne 0 ];  then
+        echo >&2 "Error installing MPFR."
+        exit 1
+    fi
 }
 
 cd src
 
 mpfr_build
+# All potential errors catched in the above function.
diff --git a/build/pkgs/openblas/spkg-check b/build/pkgs/openblas/spkg-check
--- a/build/pkgs/openblas/spkg-check
+++ b/build/pkgs/openblas/spkg-check
@@ -1,3 +1,8 @@
+if [ "$SAGE_LOCAL" = "" ]; then
+    echo >&2 "SAGE_LOCAL undefined ... exiting";
+    exit 1
+fi
+
 cd src
 
 # OpenBlas has no proper configure script
@@ -7,6 +12,9 @@ cd src
 # Therefore the following is copied from spkg-install
 # We could also patch the Makefile to use a generic symlink pointing
 # to the archive with a specific name
+
+# See #22021 for issues with multithreading
+OPENBLAS_CONFIGURE="$OPENBLAS_CONFIGURE USE_THREAD=0"
 
 if [ `python -c "from __future__ import print_function; import platform; print(platform.architecture()[0])"` = "32bit" ]; then
     OPENBLAS_CONFIGURE="$OPENBLAS_CONFIGURE BINARY=32"
@@ -19,20 +27,23 @@ fi
 
 echo "Running OpenBLAS testsuite"
 
-sdh_make tests $OPENBLAS_CONFIGURE
+$MAKE tests $OPENBLAS_CONFIGURE
 if [ $? -ne 0 ]; then
     # First make sure we already didn't set a target
     if [[ $OPENBLAS_CONFIGURE == *"TARGET"* ]]; then
-        sdh_die "Error while running the OpenBlas testsuite ... exiting"
+        echo >&2 "Error while running the OpenBlas testsuite ... exiting"
+        exit 1
     else
         # The recommended TARGET is ATOM if CPU fails
         # See https://github.com/xianyi/OpenBLAS/issues/1204
         OPENBLAS_CONFIGURE="$OPENBLAS_CONFIGURE TARGET=ATOM"
         echo "Error while testing the OpenBLAS testsuite"
         echo "Retrying the OpenBAS testsuit with TARGET=ATOM"
-        sdh_make tests $OPENBLAS_CONFIGURE
+        $MAKE tests $OPENBLAS_CONFIGURE
         if [ $? -ne 0 ]; then
-            sdh_die "Error while running the OpenBLAS testsuite ... exiting"
+            echo >&2 "Error while running the OpenBLAS testsuite ... exiting"
+            exit 1
         fi
     fi
 fi
+
diff --git a/build/pkgs/python3/spkg-build b/build/pkgs/python3/spkg-build
--- a/build/pkgs/python3/spkg-build
+++ b/build/pkgs/python3/spkg-build
@@ -31,7 +31,7 @@ if [ "$UNAME" = Darwin ]; then
     PYTHON_CONFIGURE="--disable-toolbox-glue $PYTHON_CONFIGURE"
 
     mkdir "../include"
-    if [ -n "$OPENSSL_INCLUDE" ];  then
+    if ![ -z "$OPENSSL_INCLUDE" ];  then
         # If the user explicitely states where to get the openssl
         # includes, use that.
         cp -rp "$OPENSSL_INCLUDE" "../include"
@@ -79,13 +79,23 @@ else
     PYTHON_CONFIGURE="$PYTHON_CONFIGURE --without-ensurepip"
 fi
 
-sdh_configure --enable-shared $PYTHON_CONFIGURE
+./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
+    --enable-shared $PYTHON_CONFIGURE
+
+if [ $? -ne 0 ]; then
+    echo >&2 "Error configuring Python."
+    exit 1
+fi
 
 # Make sure -L. is placed before -L$SAGE_LOCAL/lib so that python and extension
 # modules are linked with the right libpython; we pass this in at make time
 # only, since we don't want -L. to be saved as one of the default LDFLAGS
 # used for building third-party extension modules
-sdh_make LDFLAGS="-L. $LDFLAGS"
+$MAKE LDFLAGS="-L. $LDFLAGS"
+if [ $? -ne 0 ]; then
+    echo >&2 "Error building Python."
+    exit 1
+fi
 
 if [ "$UNAME" = "Darwin" ]; then
     export DYLD_LIBRARY_PATH="."
diff --git a/build/pkgs/zlib/spkg-install b/build/pkgs/zlib/spkg-install
--- a/build/pkgs/zlib/spkg-install
+++ b/build/pkgs/zlib/spkg-install
@@ -1,3 +1,9 @@
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "Error: SAGE_LOCAL undefined - exiting..."
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
+fi
+
 cd src/
 
 
@@ -5,14 +11,31 @@ if [ "$UNAME" = CYGWIN ]; then
     export BINARY_PATH="$SAGE_LOCAL/bin"
     export INCLUDE_PATH="$SAGE_LOCAL/include"
     export LIBRARY_PATH="$SAGE_LOCAL/lib"
-    cp -f win32/Makefile.gcc Makefile || \
-        sdh_die "Error copying over zlib's Makefile for Cygwin."
+    cp -f win32/Makefile.gcc Makefile
+
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error copying over zlib's Makefile for Cygwin."
+        exit 1
+    fi
 
     # We want to install shared objects
     sed -i 's/SHARED_MODE=0/SHARED_MODE=1/' Makefile
 else
-    sdh_configure --shared
+    ./configure --shared --prefix="$SAGE_LOCAL" --includedir="$SAGE_LOCAL/include"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error configuring zlib."
+        exit 1
+    fi
 fi
 
-sdh_make
-sdh_make_install
+$MAKE
+if [ $? -ne 0 ]; then
+    echo >&2 "Error building zlib."
+    exit 1
+fi
+
+$MAKE install
+if [ $? -ne 0 ]; then
+    echo >&2 "Error installing zlib."
+    exit 1
+fi
