ecl: spkg-install
- unhardcode gmp includedir
- patching
- FILELIST
- environment
- spkg-check wrapper

diff --git a/build/pkgs/ecl/spkg-install b/build/pkgs/ecl/spkg-install
--- a/build/pkgs/ecl/spkg-install
+++ b/build/pkgs/ecl/spkg-install
@@ -1,22 +1,21 @@
 #!/usr/bin/env bash
 
+# makefile compatibility kludge
+if [ "$1" = "check" ]; then
+	exec ./spkg-check
+fi
+
 if [ -z "$SAGE_LOCAL" ] ; then
     echo >&2 "Error - SAGE_LOCAL undefined ... exiting"
     echo >&2 "Maybe run 'sage -sh'?"
     exit 1
 fi
 
+CUR=`pwd`
+
+( echo "include spkg.mk" | sage-dist-make - patch-stamp ) || exit $?
+
 cd src
-# For some of the patches, Cygwin also has upstream fixes that are
-# closely related, keep track.  See Trac 11119, for example.
-for patch in ../patches/*.patch; do
-    [ -f "$patch" ] || continue
-    patch -p1 <"$patch"
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error applying '$patch'"
-        exit 1
-    fi
-done
 
 if [ -z "$CFLAG64" ] ; then
     CFLAG64=-m64
@@ -67,9 +66,9 @@ export CXXFLAGS
 export CPPFLAGS
 export LDFLAGS
 
-# Building ECL in parallel doesn't work, so use only 1 thread
+# BUG: Building ECL in parallel doesn't work, so use only 1 thread
 MAKE="$MAKE -j1"
-
+export MAKE
 
 if [ "`uname -sm`" = "SunOS i86pc" ] && [ "x$SAGE64" = xyes ]; then
     # Need to add --with-dffi=no to disable assembly code on OpenSolaris x64.
@@ -81,7 +80,15 @@ if [ "`uname -sm`" = "SunOS i86pc" ] && [ "x$SAGE64" = xyes ]; then
     ECL_CONFIGURE="--with-dffi=no $ECL_CONFIGURE"
 fi
 
-./configure --prefix="$SAGE_LOCAL" --with-gmp-prefix=$SAGE_LOCAL \
+
+GMPDIR=$(dirname $( echo "#include <gmp.h>" | gcc $CPPFLAGS -M -MP -E - | grep 'gmp\.h:$') )/..
+
+echo GMPDIR=$GMPDIR
+
+# fails if this directory exists (?!)
+rm -rf build/c
+
+./configure --prefix="$SAGE_LOCAL" --with-gmp-prefix=$GMPDIR \
     --libdir="$SAGE_LOCAL/lib" --disable-threads \
     --enable-unicode=no $ECL_CONFIGURE
 if [ $? -ne 0 ]; then
@@ -98,14 +105,11 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-# Remove old install of ECL, if any.
-rm -rf "$SAGE_LOCAL/lib/ecl-"*
-if [ $? -ne 0 ]; then
-    echo >&2 "Error - Failed to remove old ECL install ... exiting"
-    exit 1
-fi
+# don't Remove old install of ECL, if any.
+# FILELIST/unstage takes care of this
+# rm -rf "$SAGE_PREFIX/lib/ecl-"*
 
-$MAKE install
+$MAKE install INSTALL=sage-dist-install
 if [ $? -ne 0 ]; then
     echo >&2 "Error - Failed to install ECL ... exiting"
     exit 1
@@ -113,16 +117,25 @@ fi
 
 # Create symbolic link to lib/ecl-version directory.
 # Also create a symbolic link lib/ecl/ecl -> include/ecl.
-# This is important when the Sage install is moved, see Trac #14662.
-cd "$SAGE_LOCAL/lib/" && rm -f ecl && ln -s ecl-* ecl
+# This is important when the Sage build is moved, see Trac #14662.
+cd "$SAGE_PREFIX/lib/" && rm -f ecl && ln -s ecl-* ecl
 if [ $? -ne 0 ]; then
     echo >&2 "Error - Failed to create symbolic link to ECL library"
     echo >&2 "directory ... exiting"
     exit 1
 fi
+echo $SAGE_PREFIX/lib/ecl >> $FILELIST
 cd "$SAGE_LOCAL/lib/ecl" && rm -f ecl && ln -s ../../include/ecl ecl
 if [ $? -ne 0 ]; then
     echo >&2 "Error - Failed to create symbolic link to ECL include"
     echo >&2 "directory ... exiting"
     exit 1
 fi
+echo $SAGE_PREFIX/lib/ecl/ecl >> $FILELIST
+
+cd $CUR
+echo 'ECLDIR="$SAGE_PREFIX/lib/ecl/" && export ECLDIR' >> eclenv.sh
+#              WITHOUT THIS SLASH ^, maxima FAILS TO BUILD
+
+sage-dist-install -d $DESTDIR$SAGE_ETC/env.d
+sage-dist-install -t $DESTDIR$SAGE_ETC/env.d eclenv.sh
