Small fixes to openf4 build

diff --git a/build/pkgs/openf4/spkg-install b/build/pkgs/openf4/spkg-install
--- a/build/pkgs/openf4/spkg-install
+++ b/build/pkgs/openf4/spkg-install
@@ -2,7 +2,17 @@
 
 cd src
 
-./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib"
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
+./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
+    --with-gmp="$SAGE_LOCAL" --with-givaro="$SAGE_LOCAL"
 if [ $? -ne 0 ]; then
     echo >&2 "Error configuring f4."
     exit 1
@@ -14,7 +24,7 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-$MAKE -j1 install
+$MAKE install
 if [ $? -ne 0 ]; then
     echo >&2 "Error installing f4."
     exit 1
