trac 23119: when SAGE_PYTHON3=yes, build for both Python 2 and Python 3. This allows flexibility at run-time as to which version to use when running Sage.
Also add a new command "sage3" which should run Sage using Python 3.

diff --git a/build/bin/sage-pip-install b/build/bin/sage-pip-install
--- a/build/bin/sage-pip-install
+++ b/build/bin/sage-pip-install
@@ -7,6 +7,15 @@
 # This ensures that any previous installations of the same package
 # are uninstalled first.
 
+# If the environment variable SAGE_PYTHON3 is not set to "yes", then
+# build using only Python 2.
+#
+# If SAGE_PYTHON3="yes", then: if the first argument is "-2", build
+# using only Python 2; if the first argument is "-3", build using only
+# Python 3. Otherwise, build twice, once for each version of
+# Python. Note that "-2" or "-3" must be the first argument. Any
+# remaining arguments are passed on to "pip install".
+
 # Default arguments for all packages installed with `pip install`
 # --ignore-installed : Force pip to re-install package even if it thinks it's
 #                      already installed (for which it sometimes gets false
@@ -18,6 +27,24 @@
 # --isolated         : Don't read configuration files such as
 #                      ~/.pydistutils.cfg
 pip_install_flags="--ignore-installed --verbose --no-deps --no-index --isolated"
+
+if [ "$SAGE_PYTHON3" != "yes" ]; then
+    versions="2"
+    if [ "$1" = "-2" ] || [ "$1" = "-3" ] ; then
+        shift
+    fi
+else
+   if [ "$1" = "-2" ]; then
+       versions="2"
+       shift
+   elif [ "$1" = "-3" ]; then
+       versions="3"
+       shift
+   else
+       echo "pip: will install for Python 2 and 3"
+       versions="2 3"
+   fi
+fi
 
 # Consume any additional pip install arguments except the last one
 while [ $# -gt 1 ]; do
@@ -31,61 +58,57 @@ if [ "$1" != "." ]; then
     exit 1
 fi
 
+for ver in $versions
+do
+    echo "pip: now installing for Python $ver"
+    PYTHON=python$ver
+    PIP=pip$ver
 
-if [ "$SAGE_PYTHON3" = yes ]; then
-    PYTHON=python3
-    PIP=pip3
-else
-    PYTHON=python2
-    PIP=pip2
-fi
+    # Find out the name of the package that we are installing
+    name="$($PYTHON setup.py --name)"
 
-
-# Find out the name of the package that we are installing
-name="$($PYTHON setup.py --name)"
-
-if [ $? -ne 0 ]; then
-    echo >&2 "Error: could not determine package name"
-    exit 1
-fi
-
-if [ $(echo "$name" | wc -l) -gt 1 ]; then
-    name="$(echo "$name" | tail -1)"
-    echo >&2 "Warning: This package has a badly-behaved setup.py which outputs"
-    echo >&2 "more than the package name for 'setup.py --name'; using the last"
-    echo >&2 "line as the package name: $name"
-fi
-
-
-# We should avoid running pip2/3 while uninstalling a package because that
-# is prone to race conditions. Therefore, we use a lockfile while
-# running pip. This is implemented in the Python script pip2/3-lock.
-
-# Keep uninstalling as long as it succeeds
-while true; do
-    out=$($PIP-lock uninstall --disable-pip-version-check -y "$name" 2>&1)
     if [ $? -ne 0 ]; then
-        break
+        echo >&2 "Error: could not determine package name"
+        exit 1
     fi
-    echo "$out"
+
+    if [ $(echo "$name" | wc -l) -gt 1 ]; then
+        name="$(echo "$name" | tail -1)"
+        echo >&2 "Warning: This package has a badly-behaved setup.py which outputs"
+        echo >&2 "more than the package name for 'setup.py --name'; using the last"
+        echo >&2 "line as the package name: $name"
+    fi
+
+    # We should avoid running pip2/3 while uninstalling a package because that
+    # is prone to race conditions. Therefore, we use a lockfile while
+    # running pip. This is implemented in the Python script pip2/3-lock.
+
+    # Keep uninstalling as long as it succeeds
+    while true; do
+        out=$($PIP-lock uninstall --disable-pip-version-check -y "$name" 2>&1)
+        if [ $? -ne 0 ]; then
+            break
+        fi
+        echo "$out"
+    done
+
+    # Not ideal, but this is the easiest way to check if the package
+    # was not installed to begin with (which pip2/3 treats as an error).
+    # If it wasn't, then we proceed quietly; if it was installed show the
+    # uninstallation output and error out.
+    if [[ "$out" != *"not installed" ]]; then
+        echo >&2 "$out"
+        exit 1
+    fi
+
+    # Finally actually do the installation (the "SHARED" tells pip2/3-lock
+    # to apply a shared lock)
+    echo "Installing package $name using $PIP"
+
+    $PIP-lock SHARED install $pip_install_flags .
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error: installing with $PIP failed"
+        exit 3
+    fi
+
 done
-
-# Not ideal, but this is the easiest way to check if the package
-# was not installed to begin with (which pip2/3 treats as an error).
-# If it wasn't, then we proceed quietly; if it was installed show the
-# uninstallation output and error out.
-if [[ "$out" != *"not installed" ]]; then
-    echo >&2 "$out"
-    exit 1
-fi
-
-# Finally actually do the installation (the "SHARED" tells pip2/3-lock
-# to apply a shared lock)
-echo "Installing package $name using $PIP"
-
-$PIP-lock SHARED install $pip_install_flags .
-if [ $? -ne 0 ]; then
-    echo >&2 "Error: installing with $PIP failed"
-    exit 3
-fi
-
diff --git a/build/pkgs/brial/spkg-install b/build/pkgs/brial/spkg-install
--- a/build/pkgs/brial/spkg-install
+++ b/build/pkgs/brial/spkg-install
@@ -17,25 +17,33 @@ cd src
 # C++11 workaround https://trac.sagemath.org/ticket/20926
 export CXXFLAGS="$CXXFLAGS -std=c++98"
 
-export PYTHON=sage-python23
-
-./configure \
-    --prefix="$SAGE_LOCAL" \
-    --libdir="$SAGE_LOCAL/lib" \
-    --enable-shared --disable-static
-if [ $? -ne 0 ]; then
-    echo "Error configuring BRiAl"
-    exit 1
+if [ "$SAGE_PYTHON3" = "yes" ]; then
+    versions="2 3"
+else
+    versions="2"
 fi
 
-$MAKE
-if [ $? -ne 0 ]; then
-    echo "Error building BRiAl"
-    exit 1
-fi
+for ver in $versions
+do
+    export PYTHON=python$ver
+    ./configure \
+        --prefix="$SAGE_LOCAL" \
+        --libdir="$SAGE_LOCAL/lib" \
+        --enable-shared --disable-static
+    if [ $? -ne 0 ]; then
+        echo "Error configuring BRiAl"
+        exit 1
+    fi
 
-$MAKE install -j1
-if [ $? -ne 0 ]; then
-    echo "Error installing BRiAl"
-    exit 1
-fi
+    $MAKE
+    if [ $? -ne 0 ]; then
+        echo "Error building BRiAl"
+        exit 1
+    fi
+
+    $MAKE install -j1
+    if [ $? -ne 0 ]; then
+        echo "Error installing BRiAl"
+        exit 1
+    fi
+done
diff --git a/build/pkgs/gambit/spkg-install b/build/pkgs/gambit/spkg-install
--- a/build/pkgs/gambit/spkg-install
+++ b/build/pkgs/gambit/spkg-install
@@ -20,10 +20,19 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-cd src/python
-sage-python23 setup.py --no-user-cfg build install
-
-if [ $? -ne 0 ]; then
-    echo "Error installing Python API"
-    exit 1
+if [ "$SAGE_PYTHON3" = "yes" ]; then
+    versions="2 3"
+else
+    versions="2"
 fi
+
+cd src/python
+
+for ver in $versions
+do
+    python$ver setup.py --no-user-cfg build install
+    if [ $? -ne 0 ]; then
+        echo "Error installing Python $ver API"
+        exit 1
+    fi
+done
diff --git a/build/pkgs/pillow/spkg-install b/build/pkgs/pillow/spkg-install
--- a/build/pkgs/pillow/spkg-install
+++ b/build/pkgs/pillow/spkg-install
@@ -14,15 +14,24 @@ rm -rf \
    "$SAGE_LOCAL"/lib/python*/site-packages/PIL-*.egg* \
    "$SAGE_LOCAL"/lib/python*/site-packages/Pillow-*.egg*
 
-# Note: Avoid shared libraries inside egg files, Trac #19467
-sage-python23 setup.py \
-       --no-user-cfg \
-       build_ext \
-       --disable-jpeg \
-       install \
-       --single-version-externally-managed \
-       --record /dev/null
-if [ $? -ne 0 ]; then
-    echo "Error building / installing Pillow"
-    exit 1
+if [ "$SAGE_PYTHON3" = "yes" ]; then
+    versions="2 3"
+else
+    versions="2"
 fi
+
+for ver in $versions
+do
+    # Note: Avoid shared libraries inside egg files, Trac #19467
+    python$ver setup.py \
+               --no-user-cfg \
+               build_ext \
+               --disable-jpeg \
+               install \
+               --single-version-externally-managed \
+               --record /dev/null
+    if [ $? -ne 0 ]; then
+        echo "Error building / installing Pillow"
+        exit 1
+    fi
+done
diff --git a/build/pkgs/scons/spkg-install b/build/pkgs/scons/spkg-install
--- a/build/pkgs/scons/spkg-install
+++ b/build/pkgs/scons/spkg-install
@@ -10,10 +10,18 @@ cd src/
 
 rm -rf $SAGE_LOCAL/lib/scons-*
 
-# scons does not work with pip
-sage-python23 setup.py --no-user-cfg install
-
-if [ $? -ne 0 ]; then
-    echo "Error installing scons"
-    exit 1
+if [ "$SAGE_PYTHON3" = "yes" ]; then
+    versions="2 3"
+else
+    versions="2"
 fi
+
+for ver in $versions
+do
+    # scons does not work with pip
+    python$ver setup.py --no-user-cfg install
+    if [ $? -ne 0 ]; then
+        echo "Error installing scons with Python $ver"
+        exit 1
+    fi
+done
diff --git a/build/pkgs/sip/spkg-install b/build/pkgs/sip/spkg-install
--- a/build/pkgs/sip/spkg-install
+++ b/build/pkgs/sip/spkg-install
@@ -8,23 +8,32 @@ fi
 
 cd src/
 
-sage-python23 configure.py
-if [ $? -ne 0 ]
-then
-    echo "Configuration of sip failed"
-    exit 1
+if [ "$SAGE_PYTHON3" = "yes" ]; then
+    versions="2 3"
+else
+    versions="2"
 fi
 
-${MAKE}
-if [ $? -ne 0 ]
-then
-    echo "Build of sip failed"
-exit 1
-fi
+for ver in $versions
+do
+    python$ver configure.py
+    if [ $? -ne 0 ]
+    then
+        echo "Configuration of sip failed"
+        exit 1
+    fi
 
-${MAKE} install
-if [ $? -ne 0 ]
-then
-    echo "Installation of sip failed"
-    exit 1
-fi
+    ${MAKE}
+    if [ $? -ne 0 ]
+    then
+        echo "Build of sip failed"
+        exit 1
+    fi
+
+    ${MAKE} install
+    if [ $? -ne 0 ]
+    then
+        echo "Installation of sip failed"
+        exit 1
+    fi
+done
diff --git a/src/bin/sage b/src/bin/sage
--- a/src/bin/sage
+++ b/src/bin/sage
@@ -256,6 +256,7 @@ usage_advanced() {
     exit 0
 }
 
+executable=`basename $0`
 
 #####################################################################
 # Special options to be processed without sage-env
@@ -326,7 +327,7 @@ if [ "$1" = '-i' ]; then
 
     # First of all, make sure that the toolchain is up-to-date
     # (which is a dependency of every package)
-    ./sage --location
+    ./$executable --location
     $MAKE all-toolchain
     echo
 
@@ -335,7 +336,7 @@ if [ "$1" = '-i' ]; then
     do
         case "$PKG" in
             -info|--info)
-                echo >&2 "Error: 'sage -i $PKG <package>' is no longer supported, use 'sage --info <package>' instead."
+                echo >&2 "Error: '$executable -i $PKG <package>' is no longer supported, use '$executable --info <package>' instead."
                 exit 2;;
             -f) FORCE_INSTALL=yes;;
             -*) INSTALL_OPTIONS="$INSTALL_OPTIONS $PKG";;
@@ -346,7 +347,7 @@ if [ "$1" = '-i' ]; then
                     echo >&2 "Assuming it is an old-style package... (this is deprecated: use -p instead of -i to install old-style packages)"
                     echo >&2
                     sleep 5
-                    ./sage -p $INSTALL_OPTIONS "$PKG"
+                    ./$executable -p $INSTALL_OPTIONS "$PKG"
                 else
                     if [ x$FORCE_INSTALL = xyes ]; then
                         $MAKE "$PKG-clean"
@@ -360,13 +361,12 @@ fi
 
 
 #####################################################################
-# Source sage-env ($0 is the name of this "sage" script, so we can just
-# append -env to that). We redirect stdout to stderr, which is safer
+# Source sage-env. We redirect stdout to stderr, which is safer
 # for scripts.
 #####################################################################
-. "$0-env" >&2
+. "`dirname $0`/sage-env" >&2
 if [ $? -ne 0 ]; then
-    echo >&2 "Error setting environment variables by sourcing '$0-env';"
+    echo >&2 "Error setting environment variables by sourcing 'sage-env';"
     echo >&2 "possibly contact sage-devel (see http://groups.google.com/group/sage-devel)."
     exit 1
 fi
@@ -384,7 +384,7 @@ fi
 # Prepare for running Sage, either interactively or non-interactively.
 sage_setup() {
     # Check that we're not in a source tarball which hasn't been built yet (#13561).
-    if [ ! -x "$SAGE_LOCAL/bin/sage" ]; then
+    if [ ! -x "$SAGE_LOCAL/bin/$executable" ]; then
         echo >&2 '************************************************************************'
         echo >&2 'It seems that you are attempting to run Sage from an unpacked source'
         echo >&2 'tarball, but you have not compiled it yet (or maybe the build has not'
@@ -427,7 +427,7 @@ maybe_sage_location()
 # Start an interactive Sage session, this function never returns.
 interactive_sage() {
     sage_setup
-    exec sage-ipython "$@" -i
+    exec $executable-ipython "$@" -i
 }
 
 if [ "$1" = '-min' -o "$1" = '--min' ]; then
@@ -700,7 +700,7 @@ EOF
         echo >&2 "Starting subshell with Sage environment variables set.  Don't forget"
         echo >&2 "to exit when you are done.  Beware:"
         echo >&2 " * Do not do anything with other copies of Sage on your system."
-        echo >&2 " * Do not use this for installing Sage packages using \"sage -i\" or for"
+        echo >&2 " * Do not use this for installing Sage packages using \"$executable -i\" or for"
         echo >&2 "   running \"make\" at Sage's root directory.  These should be done"
         echo >&2 "   outside the Sage shell."
         echo >&2
@@ -980,13 +980,13 @@ if [ "$1" = '-gdb' -o "$1" = "--gdb" ]; then
     sage_setup
     if [ "$SAGE_DEBUG" = "no" ]; then
         gdb -x "$SAGE_LOCAL/bin/sage-gdb-commands" \
-            -args python "$SAGE_LOCAL/bin/sage-ipython" "$@" -i
+            -args python "$SAGE_LOCAL/bin/$executable-ipython" "$@" -i
     else
         # Location of cython_debug directory
         cygdb_dir="$SAGE_SRC/build/cythonized"
         cygdb "$cygdb_dir" "$SAGE_SRC/sage" \
             -- -x "$SAGE_LOCAL/bin/sage-gdb-commands" \
-            -args python "$SAGE_LOCAL/bin/sage-ipython" "$@" -i
+            -args python "$SAGE_LOCAL/bin/$executable-ipython" "$@" -i
     fi
     exit $?
 fi
