also install AtlasRep from the database_gap tarball

diff --git a/build/pkgs/database_gap/spkg-install b/build/pkgs/database_gap/spkg-install
--- a/build/pkgs/database_gap/spkg-install
+++ b/build/pkgs/database_gap/spkg-install
@@ -23,6 +23,14 @@ echo "********************************************************************"
 
 cd src/
 
+rm -rf "$SAGE_LOCAL/gap/latest/atlasrep"
+cp -rp pkg/atlasrep "$SAGE_LOCAL/gap/latest/pkg/"
+if [ $? -ne 0 ]; then
+    echo >&2 "Error installing AtlasRep database."
+    exit 1
+fi
+echo "Installed AtlasRep database."
+
 rm -rf "$SAGE_LOCAL/gap/latest/small"
 cp -rp small "$SAGE_LOCAL/gap/latest/"
 if [ $? -ne 0 ]; then
