Fix building pynac 0.6.8 on Cygwin
Technically this isn't really a Cygwin/Windows-specific issue.  The code is actually wrong, but the linker on Windows is just more sensitive to this issue.

See https://trac.sagemath.org/ticket/21265

diff --git a/build/pkgs/pynac/spkg-install b/build/pkgs/pynac/spkg-install
--- a/build/pkgs/pynac/spkg-install
+++ b/build/pkgs/pynac/spkg-install
@@ -26,7 +26,16 @@ PYNACDIR=${WORKDIR}
 
 patch()
 {
-    true
+    cd ${PYNACDIR}
+    for patch in ../patches/*.patch; do
+        [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+        patch -p1 <"$patch"
+        if [ $? -ne 0 ]; then
+            echo >&2 "Error applying '$patch'"
+            exit 1
+        fi
+    done
+    cd ${WORKDIR}
 }
 
 build_pynac()
