#19678: linking pynac to gmp under cygwin

diff --git a/build/pkgs/pynac/spkg-install b/build/pkgs/pynac/spkg-install
--- a/build/pkgs/pynac/spkg-install
+++ b/build/pkgs/pynac/spkg-install
@@ -24,9 +24,16 @@ fi
 WORKDIR=${PWD}/src
 PYNACDIR=${WORKDIR}
 
-patch()
+patch_pynac()
 {
-    true
+    for patch in ../patches/*.patch; do
+        [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+        patch -p1 <"$patch"
+        if [ $? -ne 0 ]; then
+            echo >&2 "Error applying '$patch'"
+            exit 1
+        fi
+    done
 }
 
 build_pynac()
@@ -62,10 +69,8 @@ clean_pynac()
     true
 }
 
-patch
-
-
 cd src
+patch_pynac
 
 echo "Starting build..."
 echo "Running build_pynac..."
