build/make/install: Do not ignore errors from dir2pi

diff --git a/build/make/install b/build/make/install
--- a/build/make/install
+++ b/build/make/install
@@ -143,7 +143,12 @@ fi
 
 # Update simple repository index
 if command dir2pi >&/dev/null; then
-    dir2pi "$SAGE_SPKG_WHEELS" && echo "Updated PEP 503 simple repository index in $SAGE_SPKG_WHEELS/simple"
+    if dir2pi "$SAGE_SPKG_WHEELS"; then
+        echo "Updated PEP 503 simple repository index in $SAGE_SPKG_WHEELS/simple"
+    else
+        echo "Error updating PEP 503 simple repository index"
+        exit 1
+    fi
 fi
 
 # Build succeeded.
