src/pkgs/sage_conf-relocatable: New
Fix up package_data

Closer to working

Add variable TARGETS

src/pkgs/sage_conf-relocatable/setup.py: Move the SAGE_ROOT directory away after building

src/pkgs/sage_conf-relocatable/setup.py: Use --enable-download-from-upstream-url

src/pkgs/sage_conf-relocatable/setup.py: Use --enable-fat-binary

src/pkgs/sage_conf-relocatable/tox.ini: Add environment macos-10.15

src/pkgs/sage_conf-relocatable/tox.ini: Define environments macos-python3.8, macos-python3.7, macos-python3_xcode

src/pkgs/sage_conf-relocatable/tox.ini: Run delocate-listdeps

src/pkgs/sage_conf-relocatable/setup.py: Build the wheelhouse, but --disable-notebook --disable-r --disable-sagelib

src/pkgs/sage_conf-relocatable/setup.py: Use --with-mp=gmp instead of broken --without-system-gmp option

src/pkgs/sage_conf-relocatable/setup.py: Do not package up $SAGE_LOCAL/var/tmp

src/pkgs/sage_conf-relocatable/setup.py: Use --without-system-readline

src/pkgs/sage_conf-relocatable/tox.ini (macos): Also use -isysroot with g++

src/pkgs/sage_conf-relocatable/tox.ini (macos): Add more SDK paths

tox.ini (local-macos-nohomebrew): Add to Python3.framework/Headers to CPATH

src/pkgs/sage_conf-relocatable/setup.py: Use LIBGD_CONFIGURE='--without-...almost everything...'

src/pkgs/sage_conf-relocatable: Remove settings that are now set in SAGE_ROOT/tox.ini

src/pkgs/sage_conf-relocatable/setup.py: Resolve SAGE_ROOT

src/pkgs/sage_conf-relocatable/setup.py: Unlink a previous symlink 'sage_root' in the package source tree before setting the new one

src/pkgs/sage_conf-relocatable/setup.py: Make sure that we do not package a copy of the sagelib source tree

src/pkgs/sage_conf-relocatable/setup.py: Build the wheels in a venv outside of SAGE_LOCAL

src/pkgs/sage_conf-relocatable/setup.py: Include plat_name in the directory name for SAGE_ROOT

Fixup

src/pkgs/sage_conf-relocatable/setup.py: Working version

.gitignore: Add more

src/pkgs/sage_conf-relocatable/setup.py: Fixup

src/pkgs/sage_conf-relocatable/sage_conf.py.in: Update from src/pkgs/sage_conf/

src/pkgs/sage_conf-relocatable/setup.py: Add first install_requires @ GH

src/pkgs/sage_conf-relocatable/setup.py: Add install_requires for all built binary wheels

Have sagemath_standard wheel depend on sage_conf wheel @ GH

src/pkgs/sage_conf-relocatable/setup.py: Pass CONFIGURED_{CC,CXX} to configure if set

src/pkgs/sage_conf-relocatable/setup.py: Package libexec too

src/pkgs/sage_conf-relocatable/setup.py: configure --without-system-boost...

src/pkgs/sage_conf*/README.rst: Unify the files

build/pkgs/sagelib/src/README.rst: Link to sage-conf on pypi

Signed-off-by: Matthias Koeppe <mkoeppe@math.ucdavis.edu>

Fixup: Add missing symlinks src/pkgs/sage_conf-{pypi,relocatable}/README.rst

src/pkgs/sage_conf-relocatable/setup.py: Use configure --enable-build-as-root

src/pkgs/sage_conf-relocatable/setup.py: Use configure --without-system-zeromq

src/pkgs/sage_conf-relocatable/setup.py: Move/copy/delete build trees more carefully

src/pkgs/sage_conf-relocatable/setup.py: Use wheel tags in build directory name too

src/pkgs/sage_conf-relocatable/setup.py: Do not use removed option --without-system-boost

diff --git a/build/pkgs/sagelib/spkg-install b/build/pkgs/sagelib/spkg-install
--- a/build/pkgs/sagelib/spkg-install
+++ b/build/pkgs/sagelib/spkg-install
@@ -4,6 +4,17 @@ if [ "$SAGE_EDITABLE" = yes ]; then
 else
     cd src
 fi
+
+# For type=script packages, the build rule in build/make/Makefile sources
+# sage-env but not sage-dist-helpers.
+lib="$SAGE_ROOT/build/bin/sage-dist-helpers"
+. "$lib"
+if [ $? -ne 0 ]; then
+    echo >&2 "Error: failed to source $lib"
+    echo >&2 "Is $SAGE_ROOT the correct SAGE_ROOT?"
+    exit 1
+fi
+
 ## All sagelib-building is done by setup.py.
 ## This is so that sagelib can be installed by standard Python procedures,
 ## such as "./setup.py install" or "pip install ."
@@ -54,7 +65,17 @@ if [ "$SAGE_EDITABLE" = yes ]; then
 else
     # Likewise, we should remove the egg-link that may have been installed previously.
     (cd "$SITEPACKAGESDIR" && rm -f sagemath-standard.egg-link)
-    time python3 -u setup.py --no-user-cfg build install || exit 1
+
+    if [ -n "$SAGE_CONF_WHEEL_URL" ]; then
+        # We are in wheel building mode.
+        # Need to build the wheel manually because pip does not
+        # follow symlinks.
+        sdh_setup_bdist_wheel
+        sdh_store_and_pip_install_wheel .
+    else
+        # Traditional incremental install
+        time python3 -u setup.py --no-user-cfg build install || exit 1
+    fi
 fi
 
 if [ "$UNAME" = "CYGWIN" ]; then
