initial version of CHomP spkg

diff --git a/build/pkgs/chomp/spkg-install b/build/pkgs/chomp/spkg-install
--- a/build/pkgs/chomp/spkg-install
+++ b/build/pkgs/chomp/spkg-install
@@ -10,6 +10,15 @@ fi
 
 cd src/
 
+# Apply patches.
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
 echo "Configuring $NAME..."
 ./configure \
     --prefix="$SAGE_LOCAL" \
