Now that sdh_make_install implements DESTDIR we can replace all manual calls to $MAKE install DESTDIR=... with calls to sdh_make_install.
While we're already mass-updating install scripts, this also changes
the affected scripts to use sdh_configure and sdh_make as appropriate.

In many cases this makes immediate large simplifications to those
scripts.  Even more simplification can be gained with some additional
helpers (such as setting common build variables) but those enhancements
can come as a separate change.

diff --git a/build/pkgs/r/spkg-install b/build/pkgs/r/spkg-install
--- a/build/pkgs/r/spkg-install
+++ b/build/pkgs/r/spkg-install
@@ -1,9 +1,3 @@
-if [ -z "$SAGE_LOCAL" ]; then
-    echo >&2 "SAGE_LOCAL undefined ... exiting"
-    echo >&2 "Maybe run 'sage --sh'?"
-    exit 1
-fi
-
 # r uses grep output during its build
 unset GREP_OPTIONS
 
@@ -111,27 +105,27 @@ export SAGE_BUILDING_R=yes
 
 config()
 {
-    ./configure \
-        --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
-	--enable-R-shlib \
-	--with-recommended-packages \
-        --with-readline=yes \
-        --with-x=$XSUPPORT \
-        "$R_CONFIGURE_BLAS" \
-        "$R_CONFIGURE_LAPACK" \
-        $R_CONFIGURE
+    sdh_configure --enable-R-shlib \
+                  --with-recommended-packages \
+                  --with-readline=yes \
+                  --with-x=$XSUPPORT \
+                  "$R_CONFIGURE_BLAS" \
+                  "$R_CONFIGURE_LAPACK" \
+                  $R_CONFIGURE
 }
 
-config
+# Run in a subshell in case config with X11 support fails
+(config)
 if [ $? -ne 0 ]; then
     echo "Configuring R without X11"
     XSUPPORT=no
     config
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error configuring R."
-        exit 1
-    fi
 fi
+
+restore_moved_rinstall() {
+    mv "$SAGE_LOCAL"/lib/R "$SAGE_LOCAL"/lib/R.old
+}
+
 
 if [ "$UNAME" = "Darwin" ]; then
     # We have to move (i.e., hide) old installs of R when upgrading R in Sage on OS X.
@@ -142,30 +136,14 @@ if [ "$UNAME" = "Darwin" ]; then
     # On systems using LD_LIBRARY_PATH, both Sage and R modify it and R wins,
     # so no problem should occur.
     if [ -d "$SAGE_LOCAL"/lib/R ]; then
-        RINSTALL_MOVED=yes
-        mv "$SAGE_LOCAL"/lib/R "$SAGE_LOCAL"/lib/R.old
+        trap restore_moved_rinstall ERR
     fi
 fi
 
 # Build R
-$MAKE R
-if [ $? -ne 0 ]; then
-    echo >&2 "Error building R."
-    if [ "$RINSTALL_MOVED" = yes ]; then
-        mv "$SAGE_LOCAL"/lib/R.old "$SAGE_LOCAL"/lib/R
-    fi
-    exit 1
-fi
-
+sdh_make R
 # needed for help system
-$MAKE vignettes
-if [ $? -ne 0 ]; then
-    echo >&2 "Error building vignettes."
-    if [ "$RINSTALL_MOVED" = yes ]; then
-        mv "$SAGE_LOCAL"/lib/R.old "$SAGE_LOCAL"/lib/R
-    fi
-    exit 1
-fi
+sdh_make vignettes
 
 # Remove old install
 rm -rf "$SAGE_LOCAL"/lib/r
@@ -173,12 +151,10 @@ rm -rf "$SAGE_LOCAL"/lib/R
 rm -rf "$SAGE_LOCAL"/lib/R.old
 rm -rf "$SAGE_LOCAL"/lib/libRblas.* "$SAGE_LOCAL"/lib/libRlapack.* "$SAGE_LOCAL"/lib/libR.*
 
+trap - ERR
+
 # Install new version
-$MAKE install DESTDIR="$SAGE_INST_TEMP"
-if [ $? -ne 0 ]; then
-    echo >&2 "Error installing R."
-    exit 1
-fi
+sdh_make_install
 
 if [ "$UNAME" = "Darwin" ]; then
     echo "Removing fake java and javac compiler"
