build/bin/sage-spkg, src/bin/sage: Remove support for installing old-style SPKGs

diff --git a/src/bin/sage b/src/bin/sage
--- a/src/bin/sage
+++ b/src/bin/sage
@@ -166,10 +166,6 @@ usage_advanced() {
     echo "                                 build correctly; use at your own risk"
     echo "                           -n -- reply no to prompts about experimental"
     echo "                                 and old-style packages"
-    echo "  -p [opts] [packages]-- install the given Sage packages, without dependency"
-    echo "                         checking and with support for old-style spkgs."
-    echo "                         Options are -c, -d and -s with the same meaning as"
-    echo "                         for the -i command"
     echo "  -info [packages]    -- print the SPKG.txt or SPKG.rst of the given packages,"
     echo "                         and some additional information."
     echo "  --location          -- if needed, fix paths to make Sage relocatable"
@@ -385,7 +381,7 @@ if [ "$1" = '-i' ]; then
         # See https://trac.sagemath.org/ticket/25078
         if ! echo "$ALL_TARGETS" | grep "^${PKG}$" >/dev/null; then
             echo >&2 "Error: package '$PKG' not found"
-            echo >&2 "Note: if it is an old-style package, use -p instead of -i to install it"
+            echo >&2 "Note: if it is an old-style package, installing these is no longer supported"
             exit 1
         fi
         $MAKE SAGE_SPKG="sage-spkg $INSTALL_OPTIONS" "$PKG"
@@ -942,41 +938,6 @@ if [ "$1" = '--location' ]; then
     exit 0
 fi
 
-
-install() {
-    maybe_sage_location
-
-    for PKG in "$@"
-    do
-        # Check for options
-        case "$PKG" in
-            -*)
-                INSTALL_OPTIONS="$INSTALL_OPTIONS $PKG"
-                continue;;
-        esac
-
-        PKG_NAME=`echo "$PKG" | sed -e "s/\.spkg$//"`
-        PKG_NAME=`basename "$PKG_NAME"`
-
-        sage-logger \
-            "sage-spkg $INSTALL_OPTIONS '$PKG'" "$SAGE_LOGS/$PKG_NAME.log"
-        # Do not try to install further packages if one failed
-        if [ $? -ne 0 ]; then
-            exit 1
-        fi
-    done
-    # Display a message if we actually installed something (using this
-    # file, generated by sage-spkg, is a bit of a hack though)
-    if [ -f "$SAGE_LOCAL/lib/sage-force-relocate.txt" ]; then
-        echo
-        echo "Warning: it might be needed to update the Sage library before"
-        echo "installed packages work: you should run 'make' from \$SAGE_ROOT"
-        echo "before running Sage."
-    fi
-    exit 0
-}
-
-
 if [ "$1" = '-package' -o "$1" = "--package" ]; then
     shift
     exec sage-package $@
@@ -1003,12 +964,8 @@ if [ "$1" = '-installed' -o "$1" = "--installed" ]; then
 fi
 
 if [ "$1" = '-p' ]; then
-    shift
-    # If there are no further arguments, display usage help.
-    if [ $# -eq 0 ]; then
-        exec sage-spkg
-    fi
-    install "$@"
+    echo "Error: Installing old-style SPKGs is no longer supported."
+    exit 1
 fi
 
 if [ "$1" = '-info' -o "$1" = '--info' ]; then
@@ -1110,7 +1067,8 @@ fi
 if [ $# -ge 1 ]; then
     T=`echo "$1" | sed -e "s/.*\.//"`
     if [ "$T" = "spkg" ]; then
-        install "$@"
+        echo "Error: Installing old-style SPKGs is no longer supported."
+        exit 1
     fi
     sage_setup
     unset TERM  # See Trac #12263
