Some more enhancements to the sage-dist-helpers:
- an sdh_die helper for implementing the common pattern of printing an
  error message and exiting; used to implement some of the other helpers
  and may also be useful in some of the actual install scripts

- sdh_configure can be run without the default arguments by passing '--'
  as the first argument.  Useful for using the sdh_configure helper but
  with packages that have a non-standard configure script

- sdh_make_install now uses $SAGE_SUDO, and is called with the DESTDIR=
  argument defaulting to $SAGE_INST_TEMP

diff --git a/src/bin/sage-dist-helpers b/src/bin/sage-dist-helpers
--- a/src/bin/sage-dist-helpers
+++ b/src/bin/sage-dist-helpers
@@ -3,6 +3,14 @@
 # Sage-distribution helper).  Consult the below documentation for the list of
 # available helper functions:
 #
+# - sdh_die MESSAGE
+#
+#    If the last command run exited with an error, exit the build script
+#    with the error code of the last command, and print an error message.
+#    Typically used like:
+#
+#        command || sdh_die "Command failed"
+#
 # - sdh_check_vars [VARIABLE ...]
 #
 #    Check that one or more variables are defined and non-empty, and exit with
@@ -18,8 +26,10 @@
 #
 # - sdh_configure [...]
 #
-#    Runs `./configure --prefix="$SAGE_LOCAL"`.  Additional arguments to
-#    `./configure` may be given as arguments.
+#    Runs `./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib"`.
+#    Additional arguments to `./configure` may be given as arguments.  However,
+#    if the first argument is `--` then no default arguments are given (useful
+#    for non-standard configure scripts).
 #
 # - sdh_make [...]
 #
@@ -28,10 +38,24 @@
 #
 # - sdh_make_install [...]
 #
-#    Runs `$SAGE_SUDO $MAKE install`.  Additional arguments to `make` may be
-#    given as arguments.
+#    Runs `$SAGE_SUDO $MAKE install` with DESTDIR correctly set to a temporary
+#    install directory, for staged installations.  Additional arguments to
+#    `make` may be given as arguments.
 
 set -o allexport
+
+
+sdh_die () {
+    local ret=$?
+    local msg="$@"
+    if [ $ret -ne 0 ]; then
+        echo >&2 "************************************************************"
+        echo >&2 "$msg"
+        echo >&2 "************************************************************"
+        exit $ret
+    fi
+}
+
 
 sdh_check_vars() {
     local varname
@@ -53,34 +77,30 @@ sdh_guard() {
 
 sdh_configure() {
     local ret
-    ./configure --prefix="$SAGE_LOCAL" "$@"
-    ret=$?
-    if [ $ret -ne 0 ]; then
-        echo >&2 "Error configuring $PKG_NAME"
-        exit $ret
+    local defaults
+    echo "Configuring $PKG_NAME"
+    if [ "$1" = "--" ]; then
+        defaults=()
+        shift
+    else
+        defaults=(--prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib")
     fi
+    ./configure "${defaults[@]}" "$@" || sdh_die "Error configuring $PKG_NAME"
 }
 
 
 sdh_make() {
     local ret
-    ${MAKE:-make} "$@"
-    ret=$?
-    if [ $ret -ne 0 ]; then
-        echo >&2 "Error building $PKG_NAME"
-        exit $ret
-    fi
+    echo "Building $PKG_NAME"
+    ${MAKE:-make} "$@" || sdh_die "Error building $PKG_NAME"
 }
 
 
 sdh_make_install() {
     local ret
-    $SAGE_SUDO ${MAKE:-make} install "$@"
-    ret=$?
-    if [ $ret -ne 0 ]; then
-        echo >&2 "Error installing $PKG_NAME"
-        exit $ret
-    fi
+    echo "Installing $PKG_NAME"
+    $SAGE_SUDO ${MAKE:-make} install DESTDIR="$SAGE_INST_TEMP" "$@" || \
+        sdh_die "Error installing $PKG_NAME"
 }
 
 
