minimal fix to ensure that docs build/install

diff --git a/build/pkgs/cvxopt/spkg-install b/build/pkgs/cvxopt/spkg-install
--- a/build/pkgs/cvxopt/spkg-install
+++ b/build/pkgs/cvxopt/spkg-install
@@ -33,21 +33,19 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+# install docs
 if [ "x$SAGE_SPKG_INSTALL_DOCS" = xyes ] ; then
    cd doc
-# This part would be used to build the documentation with sphinx.
-# cvxopt would then have to depend on sphinx.
-# in 1.1.5 the documentation is shipped already built and up to date.
-#   ${MAKE} -B html
-#   if [ $? -ne 0 ]; then
-#      echo "Error building the documentation"
-#      exit 1
-#   fi
+   ${MAKE} -B html
+   if [ $? -ne 0 ]; then
+      echo "Error building the documentation"
+      exit 1
+   fi
 # checking to see if there is previously installed documentation.
    if [ -d $SAGE_LOCAL/share/doc/cvxopt/html ] ; then
       rm -rf $SAGE_LOCAL/share/doc/cvxopt/html
    fi
    mkdir -p $SAGE_LOCAL/share/doc/cvxopt/html
-   cp -r html/* $SAGE_LOCAL/share/doc/cvxopt/html/
+   cp -r build/html/* $SAGE_LOCAL/share/doc/cvxopt/html/
 fi
 
