Classes DegenerateManifold and DegenerateSubmanifold

diff --git a/build/pkgs/sympow/spkg-install b/build/pkgs/sympow/spkg-install
--- a/build/pkgs/sympow/spkg-install
+++ b/build/pkgs/sympow/spkg-install
@@ -1,3 +1,10 @@
+if [ "$SAGE_LOCAL" = "" ]; then
+   echo >&2 "SAGE_LOCAL undefined ... exiting"
+   echo >&2 "Maybe run 'sage -sh'?"
+   exit 1
+fi
+
+
 #######################################################################
 # Fix FPU precision
 #######################################################################
@@ -70,7 +77,8 @@ echo "CFLAGS for SYMPOW:$CFLAGS"
 
 config/fpubits
 status=$?
-[ $status -eq 1 ] && sdh_die <<_EOF_
+if [ $status -eq 1 ]; then
+cat >&2 <<EOF
 Error: the Quad Double library used by SYMPOW assumes IEEE-754 double
 precision numbers with exactly 53 bits in the mantissa (64 bits in
 total).  Unfortunately, this is not the case on your system and we
@@ -81,55 +89,72 @@ Please report this problem to sage-devel
 (http://groups.google.com/group/sage-devel), mentioning in particular
 your operating system, processor type and compiler version
 (run $CC --version).
-_EOF_
-
-[ $status -ne 0 ] && sdh_die <<_EOF_
+EOF
+elif [ $status -ne 0 ]; then
+cat >&2 <<EOF
 Error: something very bad happened while checking the precision of your
 FPU.  Please report this problem (mentioning any error messages above)
 to sage-devel (http://groups.google.com/group/sage-devel).
 Mention in particular your operating system and compiler version
 (run $CC --version).
-_EOF_
-
+EOF
+exit 1
+fi
 
 #######################################################################
 # Configure
 #######################################################################
 cd src/
-# Force bash as shell
-bash ./Configure || sdh_die "Error configuring SYMPOW"
+bash ./Configure  # Force bash as shell
+if [ $? -ne 0 ]; then
+   echo >&2 "Error configuring SYMPOW"
+   exit 1
+fi
+
 
 #######################################################################
 # Build
 #######################################################################
-sdh_make
+$MAKE
+if [ $? -ne 0 ]; then
+   echo >&2 "Error building SYMPOW"
+   exit 1
+fi
 
 #######################################################################
 # Install
 #######################################################################
 TARGET="$SAGE_LOCAL/lib/sympow"
 
-# Remove old install if any
 rm -rf "$TARGET"
+mkdir "$TARGET"
 
-sdh_install sympow *.gp new_data datafiles "$TARGET"
+cp sympow *.gp new_data "$TARGET/"
+if [ $? -ne 0 ]; then
+   echo >&2 "Error copying SYMPOW files"
+   exit 1
+fi
+
+# Copy datafiles
+mv datafiles "$TARGET/"
+if [ ! -d "$TARGET/datafiles" ]; then
+   echo >&2 "Error installing SYMPOW datafiles"
+   exit 1
+fi
 
 # Create binary versions of datafiles
-# Note: This should probably be a post-install step since it requires calling
-# the compiled sympow binary; however in this case it happens to work fine
-# since it does not have any external dependencies and can run from the temp
-# install dir
-cd "${SAGE_DESTDIR}${TARGET}/datafiles"
+cd "$TARGET/datafiles"
 for file in *.txt; do
     NUM=`grep -c AT $file`
-    ../sympow -txt2bin "$NUM" <$file ${file/%txt/bin} || \
-        sdh_die "Error running SYMPOW"
+    ../sympow -txt2bin "$NUM" <$file ${file/%txt/bin}
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error running SYMPOW"
+        exit 1
+    fi
 done
 
 # Create sympow script in $SAGE_LOCAL/bin
-BIN="$SAGE_DESTDIR_LOCAL/bin"
-mkdir -p "$BIN"
-SCRIPT="$BIN/sympow"
+SCRIPT="$SAGE_LOCAL/bin/sympow"
 
 cat >"$SCRIPT" <<'EOF'
 cd "$SAGE_LOCAL/lib/sympow"
diff --git a/build/pkgs/tides/spkg-install b/build/pkgs/tides/spkg-install
--- a/build/pkgs/tides/spkg-install
+++ b/build/pkgs/tides/spkg-install
@@ -1,8 +1,14 @@
 cd src
 
-sdh_configure
+./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib"
+if [ $? -ne 0 ]; then
+    echo >&2 "Error configuring TIDES."
+    exit 1
+fi
 
-# * Use $SAGE_LOCAL/include instead of hardcoded /usr/local/include
-# * Disable -m64 from CFLAGS and FFLAGS (which may be set even on 32-bit
-#   systems)
-sdh_make_install AM_CPPFLAGS="-I '$SAGE_LOCAL/include'" AM_CFLAGS="" AM_FFLAGS=""
+# Use $SAGE_LOCAL/include instead of hardcoded /usr/local/include
+$MAKE AM_CPPFLAGS="-I '$SAGE_LOCAL/include'" install
+if [ $? -ne 0 ]; then
+    echo >&2 "Error installing TIDES."
+    exit 1
+fi
