Replace symbolic links with their target
Linux symbolic links do not work under Windows

diff --git a/build/pkgs/python2/spkg-check b/build/pkgs/python2/spkg-check
--- a/build/pkgs/python2/spkg-check
+++ b/build/pkgs/python2/spkg-check
@@ -1,1 +1,8 @@
-../python3/spkg-check
+cd src
+$MAKE test
+
+if [ $? -ne 0 ]; then
+    echo "An error occurred while testing Python"
+    exit 1
+fi
+
