Move the post-build tests of module imports to spkg-build instead of spkg-install.
The tests are now run out of the build directory, and if they fail then build
should be considered failed, without proceeding to installation.

diff --git a/build/pkgs/python2/spkg-build b/build/pkgs/python2/spkg-build
--- a/build/pkgs/python2/spkg-build
+++ b/build/pkgs/python2/spkg-build
@@ -82,3 +82,38 @@ if [ "$UNAME" = "Darwin" ]; then
         exit 1
     fi
 fi
+
+if [ "$UNAME" = "CYGWIN" ]; then
+    EXE=".exe"
+elif [ "$UNAME" = "Linux" ]; then
+    export LD_LIBRARY_PATH="."
+fi
+
+# Make sure extension modules were built correctly.
+# All these modules are important and if any one
+# fails to build, Sage will not work.
+
+echo "Testing importing of various modules..."
+import_errors=false
+for module in ctypes math hashlib crypt readline socket ; do
+    if ./python${EXE} -c "import $module"; then
+        echo "$module module imported OK"
+    else
+        echo >&2 "$module module failed to import"
+        import_errors=true
+    fi
+done
+
+if [ "$UNAME" = "Darwin" ]; then
+    if ./python${EXE} -c "import _scproxy"; then
+        echo "_scproxy module imported OK"
+    else
+        echo >&2 "_scproxy module failed to import"
+        import_errors=true
+    fi
+fi
+
+if $import_errors; then
+    echo >&2 "Error: One or more modules failed to import."
+    exit 1
+fi
