Split spkg-install for python2/3 into spkg-build and spkg-install as recommended in https://trac.sagemath.org/ticket/21726

diff --git a/build/pkgs/python3/spkg-install b/build/pkgs/python3/spkg-install
--- a/build/pkgs/python3/spkg-install
+++ b/build/pkgs/python3/spkg-install
@@ -2,14 +2,6 @@
 ## Python
 ###########################################
 
-CUR=`pwd`
-
-if [ -z "$SAGE_LOCAL" ]; then
-    echo >&2 "SAGE_LOCAL undefined ... exiting"
-    echo >&2 "Maybe run 'sage -sh'?"
-    exit 1
-fi
-
 # It is best to unset these environment variables, as they might confuse
 # the Python installer.
 unset PYTHONHOME
@@ -21,92 +13,28 @@ export SVNVERSION=no
 
 cd src
 
-if [ "$SAGE_DEBUG" = "yes" ]; then
-    echo "Building Python with pydebug"
-    PYTHON_CONFIGURE="$PYTHON_CONFIGURE --with-pydebug"
+
+# Remove old libraries
+rm -f "$SAGE_LOCAL"/lib/libpython3*
+
+# Running 'make install' in parallel is a bad idea, so we use
+# only 1 job.
+# The "-i" option to ignore errors is crucial, especially in the
+# case of upgrades.
+$MAKE -i -j1 install
+if [ $? -ne 0 ]; then
+    echo >&2 "Error installing Python."
+    exit 1
 fi
 
-# pymalloc screws with valgrind, so let's disable it
-if [ "$SAGE_VALGRIND" = "yes" ]; then
-    echo "Building Python without pymalloc"
-    PYTHON_CONFIGURE="$PYTHON_CONFIGURE --without-pymalloc"
+echo "Installing valgrind suppression file..."
+mkdir -p "$SAGE_EXTCODE/valgrind"
+cp Misc/valgrind-python.supp "$SAGE_EXTCODE/valgrind/python3.supp"
+if [ $? -ne 0 ]; then
+    echo >&2 "Error installing valgrind suppression file."
+    exit 1
 fi
 
-if [ "$UNAME" = Darwin ]; then
-    if [ $MACOSX_VERSION -ge 16 ]; then
-        echo "OS X 10.$[$MACOSX_VERSION-4] Building with clang."
-        CC=clang
-    fi
-elif [ "$UNAME" = SunOS ]; then
-    # Enable some C99 features on Solaris. This in particular enables
-    # the isinf() and isfinite() functions. It works both for C and
-    # C++ code (which is not true for -std=c99).  See
-    # http://trac.sagemath.org/sage_trac/ticket/14265
-    export CFLAGS="-D__C99FEATURES__ $CFLAGS"
-fi
-
-if [ "$SAGE64" = yes ]; then
-    echo "64 bit build of Python enabled"
-    export CC="$CC -m64"
-fi
-
-
-build()
-{
-    # Note: --without-ensurepip ensures that setuptools+pip are *not* installed
-    # automatically when installing python3. They will be installed instead by
-    # the separate setuptools and pip packages; see
-    # https://trac.sagemath.org/ticket/23398
-    ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
-        --enable-shared --without-ensurepip $PYTHON_CONFIGURE
-
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error configuring Python."
-        exit 1
-    fi
-
-    $MAKE
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error building Python."
-        exit 1
-    fi
-
-    # On OS X, test to see if _scproxy built before installing.
-    if [ "$UNAME" = "Darwin" ]; then
-        if [ -z `find build -name _scproxy*.so` ]; then
-            echo >&2 "Error: the _scproxy module failed to build."
-            exit 1
-        fi
-    fi
-
-    # Remove old libraries
-    rm -f "$SAGE_LOCAL"/lib/libpython3*
-
-    # Running 'make install' in parallel is a bad idea, so we use
-    # only 1 job.
-    # The "-i" option to ignore errors is crucial, especially in the
-    # case of upgrades.
-    $MAKE -i -j1 install
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error installing Python."
-        exit 1
-    fi
-
-    echo "Installing valgrind suppression file..."
-    mkdir -p "$SAGE_EXTCODE/valgrind"
-    cp Misc/valgrind-python.supp "$SAGE_EXTCODE/valgrind/python3.supp"
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error installing valgrind suppression file."
-        exit 1
-    fi
-}
-
-
-# Remove old symbolic link: it is not needed and its presence can
-# interfere with the Python build.
-rm -f "$SAGE_LOCAL/lib/python"
-
-build
 
 PYTHON_VERSION=$("$SAGE_LOCAL/bin/python3" -c 'import sys; print("%d.%d" % sys.version_info[:2])')
 PYTHON_ABIFLAGS=$("$SAGE_LOCAL/bin/python3" -c 'import sys; print(sys.abiflags)')
