updated spkg-install (make -> make install), removed class Treedecomposition (-> g.name())

diff --git a/build/pkgs/tdlib/spkg-install b/build/pkgs/tdlib/spkg-install
--- a/build/pkgs/tdlib/spkg-install
+++ b/build/pkgs/tdlib/spkg-install
@@ -11,23 +11,19 @@ cp sage_tdlib.hpp src/src/
 
 cd src
 
-./configure --prefix="$SAGE_LOCAL" && $MAKE
+./configure \
+    --prefix="$SAGE_LOCAL" \
+    --libdir="$SAGE_LOCAL/lib" \
+    --enable-shared --disable-static
 
+$MAKE
 if [ $? -ne 0 ]; then
-    echo >&2 "Failed to compile tdlib"
+    echo "Error building tdlib"
     exit 1
 fi
 
-rm -rf "$SAGE_LOCAL/include/tdlib/"
-mkdir "$SAGE_LOCAL/include/tdlib/"
-cp src/sage_tdlib.hpp "$SAGE_LOCAL/include/tdlib/"
-
-if [ "$UNAME" = "Darwin" ]; then
-    cp -f ./.libs/libtd.dylib "$SAGE_LOCAL/lib/libtd.dylib"
-elif [ "$UNAME" = "CYGWIN" ]; then
-    cp -f ./.libs/libtd.so "$SAGE_LOCAL/lib/libtd.dll"
+$MAKE install -j1
+if [ $? -ne 0 ]; then
+    echo "Error installing tdlib"
+    exit 1
 fi
-
-# Copy this in all cases, in any case it doesn't hurt.
-cp -f ./.libs/libtd.so "$SAGE_LOCAL/lib/libtd.so"
-cp -f ./.libs/libtd.so.0 "$SAGE_LOCAL/lib/libtd.so.0"
