Check that FSF config.* scripts are correctly copied from SAGE_ROOT/config.

diff --git a/build/pkgs/iml/spkg-install b/build/pkgs/iml/spkg-install
--- a/build/pkgs/iml/spkg-install
+++ b/build/pkgs/iml/spkg-install
@@ -33,6 +33,11 @@ fi
 
 # Currently config.[guess|sub] scripts are too old
 cp "$SAGE_ROOT"/config/config.* config/
+if [ $? -ne 0 ]; then
+    echo >&2 "Failed to copy up-to-date FSF config.* scripts from"
+    echo >&2 "\$SAGE_ROOT/config directory ... exiting"
+    exit 1
+fi
 
 if [ -d "$SAGE_LOCAL/include/atlas" ]; then
     # We actually installed ATLAS
