.github/workflows/integration.yml: Separate job baseline_test

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -83,9 +83,62 @@ jobs:
         run: |
           EXTRA_DOCKER_BUILD_ARGS="--build-arg BUILDKIT_INLINE_CACHE=1 --build-arg USE_MAKEFLAGS=\"-k V=0 SAGE_NUM_THREADS=3 SAGE_DOCTEST_RANDOM_SEED=0\"" tox -e $TOX_ENV -- $TARGETS
 
-  integration:
+  baseline_test:
     runs-on: ubuntu-latest
     needs: [baseline_build]
+    env:
+      DOCKER_TARGETS: with-targets-optional
+    steps:
+      - name: free disk space
+        run: |
+          df -h
+          sudo swapoff -a
+          sudo rm -f /swapfile
+          sudo apt-get clean
+          docker rmi $(docker image ls -aq)
+          echo "Largest packages:"
+          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 50
+          sudo apt-get --fix-broken --yes remove $(dpkg-query -f '${Package}\n' -W | grep -E '^(ghc-|google-cloud-sdk|google-chrome|firefox|mysql-server|dotnet-sdk|hhvm|mono)') || echo "(error ignored)"
+          df -h
+      - name: Install test prerequisites
+        run: |
+          sudo DEBIAN_FRONTEND=noninteractive apt-get update
+          sudo DEBIAN_FRONTEND=noninteractive apt-get install tox
+          sudo apt-get clean
+          df -h
+      - name: Try to login to ghcr.io
+        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
+        run: |
+            TOKEN="${{ secrets.DOCKER_PKG_GITHUB_TOKEN }}"
+            if [ -z "$TOKEN" ]; then
+              TOKEN="${{ secrets.GITHUB_TOKEN }}"
+            fi
+            if echo "$TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin; then
+              echo "DOCKER_PUSH_REPOSITORY=ghcr.io/${{ github.repository }}/" >> $GITHUB_ENV
+              echo "DOCKER_CONFIG_FILE=$HOME/.docker/config.json" >> $GITHUB_ENV
+            fi
+            # From the docker documentation via .ci/update-env.sh:
+            # "A tag name must be valid ASCII and may
+            # contain lowercase and uppercase letters, digits, underscores, periods and
+            # dashes. A tag name may not start with a period or a dash and may contain a
+            # maximum of 128 characters."
+            EXTRA_DOCKER_TAGS=`echo $GITHUB_REF_NAME | tr -d '[:space:]' | tr -c '[:alnum:]_.-' '-' | sed 's/^[-.]*//' | cut -c1-128`
+            shopt -s extglob
+            case "$GITHUB_REF_NAME" in
+              +([0-9]).+([0-9])?(.+([0-9])) )
+                EXTRA_DOCKER_TAGS="latest dev $EXTRA_DOCKER_TAGS";;
+              +([0-9]).+([0-9])?(.+([0-9])).@(beta|rc)+([0-9]) )
+                EXTRA_DOCKER_TAGS="dev $EXTRA_DOCKER_TAGS";;
+            esac
+            echo "EXTRA_DOCKER_TAGS=$EXTRA_DOCKER_TAGS" >> $GITHUB_ENV
+      - name: Test integration baseline
+        run: |
+          git checkout integration-baseline
+          EXTRA_DOCKER_BUILD_ARGS="--build-arg BUILDKIT_INLINE_CACHE=1 --build-arg USE_MAKEFLAGS=\"-k V=0 SAGE_NUM_THREADS=3 SAGE_DOCTEST_RANDOM_SEED=0\"" tox -e $TOX_ENV -- $TARGETS
+
+  integration:
+    runs-on: ubuntu-latest
+    needs: [baseline_test]
     env:
       # In addition to the following packages, also "with-targets-optional-repo"
       # is pushed to GitHub packages.
@@ -163,7 +216,7 @@ jobs:
                 EXTRA_DOCKER_TAGS="dev $EXTRA_DOCKER_TAGS";;
             esac
             echo "EXTRA_DOCKER_TAGS=$EXTRA_DOCKER_TAGS" >> $GITHUB_ENV
-      - name: Test integration baseline
+      - name: Obtain integration baseline
         run: |
           git checkout integration-baseline
           EXTRA_DOCKER_BUILD_ARGS="--build-arg BUILDKIT_INLINE_CACHE=1 --build-arg USE_MAKEFLAGS=\"-k V=0 SAGE_NUM_THREADS=3 SAGE_DOCTEST_RANDOM_SEED=0\"" tox -e $TOX_ENV -- $TARGETS
