Add SAGE_SUDO for packages A-L

diff --git a/build/pkgs/latte_int/spkg-install b/build/pkgs/latte_int/spkg-install
--- a/build/pkgs/latte_int/spkg-install
+++ b/build/pkgs/latte_int/spkg-install
@@ -15,11 +15,21 @@ cd src
 CXXFLAGS="-DNTL_STD_CXX $CXXFLAGS"
 export CXXFLAGS
 ./configure --prefix=$SAGE_LOCAL --enable-shared=yes --enable-static=false --with-gmp=$SAGE_LOCAL --with-ntl=$SAGE_LOCAL --with-cddlib=$SAGE_LOCAL --with-4ti2=$SAGE_LOCAL --with-lidia=$SAGE_LOCAL
-$MAKE
-$MAKE install
+if [ $? -ne 0 ]; then
+   echo "Error configuring latte-int"
+   exit 1
+fi
 
+$MAKE
 if [ $? -ne 0 ]; then
    echo "Error building latte-int"
    exit 1
 fi
+
+$SAGE_SUDO $MAKE install
+if [ $? -ne 0 ]; then
+   echo "Error installing latte-int"
+   exit 1
+fi
+
 
