bla

diff --git a/build/pkgs/fflas_ffpack/spkg-install b/build/pkgs/fflas_ffpack/spkg-install
--- a/build/pkgs/fflas_ffpack/spkg-install
+++ b/build/pkgs/fflas_ffpack/spkg-install
@@ -19,109 +19,44 @@ for patch in ../patches/*.patch; do
     fi
 done
 
-
-export CFLAGS="-g -O2 -fPIC $CFLAGS"
-export CXXFLAGS="-g -O2 -fPIC $CXXFLAGS"
+if [ "$SAGE_DEBUG" = "yes" ]; then
+    echo "Building a debug version of fflas-ffpack."
+    export CFLAGS="-O0 -g -fPIC $CFLAGS"
+    export CXXFLAGS="-O0 -g -fPIC $CFLAGS"
+else
+    export CXXFLAGS="-O2 -g -fPIC $CXXFLAGS"
+    export CXXFLAGS="-O0 -g -fPIC $CXXFLAGS"
+fi
 
 if [ "$SAGE64" = "yes" ]; then
-   echo "64 bit build"
-   CFLAGS="-m64 $CFLAGS "; export CFLAGS
-   CXXFLAGS="-m64 $CXXFLAGS "; export CXXFLAGS
-   CPPFLAGS="-m64 $CPPFLAGS "; export CPPFLAGS
-   LDFLAGS="-m64"; export LDFLAGS
+   echo "Building a 64 bit version of fflas-ffpack."
+   CFLAGS="-m64 $CFLAGS"
+   CXXFLAGS="-m64 $CXXFLAGS"
 fi
 
 
-if [ "$LINBOX_BLAS" != "" ]; then
-
-    echo "Using environment variable LINBOX_BLAS "$LINBOX_BLAS""
-
-elif [ $UNAME = "Darwin" -a -f "/usr/lib/libcblas.dylib" ]; then
-
-    LINBOX_BLAS=/usr/lib/libcblas.dylib
-
-elif [ $UNAME = "Linux" -a -f "${SAGE_LOCAL}/lib/libcblas.so" ]; then
-
-    echo "Linux cblas"
-
-    LINBOX_BLAS="-lcblas -latlas"
-
-elif [ $UNAME = "CYGWIN" ]; then
-
-    echo "Using system-wide Cygwin LAPACK BLAS."
-    if [ ! -f "/usr/lib/libblas.a" ]; then
-        echo "*************************************************"
-        echo "*"
-        echo "* On Cygwin you must install the standard LAPACK Cygwin package"
-        echo "* via the Cygwin setup.exe program in the 'Math' category."
-        echo "*"
-        echo "*************************************************"
-        exit 1
-    fi
-    LINBOX_BLAS="-lblas "
-
-elif [ $UNAME = "SunOS" -a -f "${SAGE_LOCAL}/lib/libcblas.so" ]; then
-
-    echo "Solaris cblas"
-
-    LINBOX_BLAS="-lcblas -latlas"
-
-elif [ $UNAME = "FreeBSD" -a -f "${SAGE_LOCAL}/lib/libcblas.a" ]; then
-
-    echo "FreeBSD cblas"
-
-    LINBOX_BLAS="-lcblas -latlas"
-
-elif [ $UNAME = "FreeBSD" -a -f "${SAGE_LOCAL}/lib/libcblas.so" ]; then
-
-    echo "FreeBSD cblas"
-
-    LINBOX_BLAS="-lcblas -latlas"
-
-else
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "using frickin' slow GSL C-blas"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-
-    if [ $UNAME = "Darwin" ]; then
-        LINBOX_BLAS="$SAGE_LOCAL"/lib/libgslcblas.dylib
-    else
-        LINBOX_BLAS="$SAGE_LOCAL"/lib/libgslcblas.so
-    fi
-
+if [ $UNAME = "SunOS" ]; then
+    FFLASFFPACK_CONFIGURE="--with-blas=\"-llapack -lcblas -latlas -lrt\" $FFLASFFPACK_CONFIGURE"
 fi
-
-echo "*************************************************"
-echo " Using LINBOX_BLAS=$LINBOX_BLAS"
-echo "*************************************************"
 
 ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
     --with-default="$SAGE_LOCAL" \
-    --with-blas="$LINBOX_BLAS" \
-    --enable-optimization --disable-static
-
+    --enable-optimization --disable-static \
+    $FFLASFFPACK_CONFIGURE
 if [ $? -ne 0 ]; then
-    echo "Error configuring linbox"
+    echo >&2 "Error configuring fflas-ffpack"
     exit 1
 fi
 
 $MAKE
 if [ $? -ne 0 ]; then
-    echo "Error building linbox"
+    echo >&2 "Error building fflas-ffpack"
+    exit 1
 fi
 
 $MAKE install
 if [ $? -ne 0 ]; then
-    echo "Error installing linbox"
+    echo >&2 "Error installing fflas-ffpack"
     exit 1
 fi
-
-echo $LINBOX_BLAS > $SAGE_LOCAL/share/cblas_config
 
