Simplify fflas_ffpack to work by autodetection on usual systems.
This should include: Linux and surely OS X and Cygwin at least.

diff --git a/build/pkgs/fflas_ffpack/spkg-install b/build/pkgs/fflas_ffpack/spkg-install
--- a/build/pkgs/fflas_ffpack/spkg-install
+++ b/build/pkgs/fflas_ffpack/spkg-install
@@ -20,90 +20,51 @@ for patch in ../patches/*.patch; do
 done
 
 
-export CFLAGS="-g -O2 -fPIC $CFLAGS"
-export CXXFLAGS="-g -O2 -fPIC $CXXFLAGS"
+CFLAGS="-g -O2 -fPIC $CFLAGS"
+CXXFLAGS="-g -O2 -fPIC $CXXFLAGS"
 
 if [ "$SAGE64" = "yes" ]; then
-   echo "64 bit build"
-   CFLAGS="-m64 $CFLAGS "; export CFLAGS
-   CXXFLAGS="-m64 $CXXFLAGS "; export CXXFLAGS
-   CPPFLAGS="-m64 $CPPFLAGS "; export CPPFLAGS
-   LDFLAGS="-m64"; export LDFLAGS
+   echo "Building a 64 bit version of fflas_ffpack."
+   CFLAGS="-m64 $CFLAGS"
+   CXXFLAGS="-m64 $CXXFLAGS"
+   LDFLAGS="-m64 $LDFLAGS"
 fi
 
+export CFLAGS CXXFLAGS LDFLAGS
 
-if [ "$LINBOX_BLAS" != "" ]; then
+# FFLAS_FFPACK expect BLAS and LAPACK C interfaces
+# To configure BLAS/LAPACK, either:
+# - rely on automatic detection system,
+# - pass every linking flags for BLAS and LAPACK in --with-blas,
+# - pass linking flags for BLAS in --with-cblas and/or flags for
+#   LAPACK in --with-lapack.
 
-    echo "Using environment variable LINBOX_BLAS "$LINBOX_BLAS""
+#if [ -z "$FFLAS_FFPACK_BLAS" ]; then
+#    FFLAS_FFPACK_BLAS=`cat "$SAGE_LOCAL/share/cblas_config"`
+#fi
+#
+#echo "*************************************************"
+#echo " Using FFLAS_FFPACK_BLAS=$FFLAS_FFPACK_BLAS"
+#echo "*************************************************"
 
-elif [ $UNAME = "Darwin" -a -f "/usr/lib/libcblas.dylib" ]; then
-
-    LINBOX_BLAS=-lcblas
-
-elif [ $UNAME = "CYGWIN" ]; then
-
-    echo "Using system-wide Cygwin LAPACK BLAS."
-    if [ ! -f "/usr/lib/libblas.a" ]; then
-        echo "*************************************************"
-        echo "*"
-        echo "* On Cygwin you must install the standard LAPACK Cygwin package"
-        echo "* via the Cygwin setup.exe program in the 'Math' category."
-        echo "*"
-        echo "*************************************************"
-        exit 1
-    fi
-    LINBOX_BLAS="-lblas "
-
-elif [ -f "${SAGE_LOCAL}/lib/libcblas.so" ]; then
-
-    echo "ATLAS"
-
-    LINBOX_BLAS="-lcblas -latlas"
-
-elif [ -f "${SAGE_LOCAL}/lib/libcblas.a" ]; then
-
-    echo "Static ATLAS"
-
-    LINBOX_BLAS="-lcblas -latlas"
-
-else
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "using frickin' slow GSL C-blas"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-
-    LINBOX_BLAS=-lgslcblas
-
-fi
-
-echo "*************************************************"
-echo " Using LINBOX_BLAS=$LINBOX_BLAS"
-echo "*************************************************"
 
 ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
     --with-default="$SAGE_LOCAL" \
-    --with-blas="$LINBOX_BLAS" \
+#    --with-blas="$FFLAS_FFPACK_BLAS" \
     --enable-optimization --disable-static
-
 if [ $? -ne 0 ]; then
-    echo "Error configuring linbox"
+    echo >&2 "Error configuring fflas_ffpack."
     exit 1
 fi
 
 $MAKE
 if [ $? -ne 0 ]; then
-    echo "Error building linbox"
+    echo >&2 "Error building fflas_ffpack."
 fi
 
 $MAKE install
 if [ $? -ne 0 ]; then
-    echo "Error installing linbox"
+    echo >&2 "Error installing fflas_ffpack."
     exit 1
 fi
 
